RESIZE_HEIGHT: 32
RESIZE_WIDTH: 32
MEAN:
  - 0.3589 
  - 0.3177 
  - 0.3357
STD:
  - 0.1457
  - 0.1530
  - 0.1624
BATCH_SIZE: 256
SEED: 1773
OPTIMIZER: SGD
SCHEDULER: ReduceLROnPlateau
LR: 0.01
WD: 0.0005
MOMENTUM: 0.9
EPOCHS: 100
MODEL_NAME: "3"
SAVE_EVERY_EPOCH: 10
