DATA_ROOT: "data"
NUM_CLASSES: 43
RESIZE_HEIGHT: 32
RESIZE_WIDTH: 32
MEAN:
  - 0.3586
  - 0.3175
  - 0.3354
STD:
  - 0.1454
  - 0.1528
  - 0.1621
BATCH_SIZE: 256
SEED: 1773
OPTIMIZER: SGD
SCHEDULER: ReduceLROnPlateau
LR: 0.01
WD: 0.0005
MOMENTUM: 0.9
EPOCHS: 100
MODEL_NAME: "VGG11"
SAVE_EVERY_EPOCH: 10
